version: '3'

includes:
  ci: ./tasks/ci.yml

tasks:
  default:
    cmds:
      - task --list
    silent: true
    desc: "List all available tasks"

  ci:
    cmds:
      - task: ci:all
    silent: true
    desc: "Run all CI checks"
